### ISSUE TITLE
Save/Load git changes? 

### ISSUE THREAD

**Issue by kristijanhusak** [chrisallenlane/vim-git-session#1]
Hi,

Does this plugin also handle saving/restoring git state?
For example, if I'm in the middle of the work, i either need to do wip commit or stash. Would be cool if that flow is also part of this process. 

Something like this : 
Create wip commit on Save
Do what you need to do
Go back to branch 
Hit load, it returns session and it resets the last commit so you are in the same state you left

**Comment by chrisallenlane** [comment]
Hi, @kristijanhusak 

> Does this plugin also handle saving/restoring git state?

It does not. The purpose of this plugin is solely to manage `vim` session state - it is not intended to provide a wrapper around `git`.

That said, if you're looking for a good wrapper around `git`, you should check out [fugitive][] by Tim Pope. I use it personally and can recommend it.

[fugitive]: https://github.com/tpope/vim-fugitive
